# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'
  demands: 
  - npm

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.300'
  inputs: 
    version: '3.1.300'
-
- task: Npm@1
  displayName: 'Run NPM Install'
  inputs:
    command: 'install'

- task: gulp@0
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 
    gulpjs: 'node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false

- task: CmdLine@2
  inputs:
    script: '"$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'''
    workingDirectory: 'Tailspin.SpaceGame.Web/wwwroot'
  
- task: DotNetCoreCLI@2
  displayName: Restore project dependencies
  inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'

